### ISSUE TITLE
Autosort speakers by for, against, or neutral

### ISSUE THREAD

**Issue by MPham95** [MaxwellBo/Muncoordinated-2#10]
As a Director, I can ask for 1 delegate for, 1 delegate against, and 1 delegate neutral, and then having to repeat the call instead of just asking for all for speakers, all against speakers, and all neutral speakers and then reordering them or sorting them myself

**Comment by MaxwellBo** [comment]
Closed by 89c8dbc704fbbad5d3f9101d6f6767c0c0f42b1e
