### ISSUE TITLE
Direct Voting on Motions

### ISSUE THREAD

**Issue by SharanVaidy** [MaxwellBo/Muncoordinated-2#121]
### Problem
The biggest issue my school's MUN faces with virtual Model UN is direct voting on motions since there's no option to vote on the 'Motions' page.
### Proposed Solution
It might be a good idea to add the exact same strawpoll-like voting feature with each proposed motion.
### Alternatives
Right now, we're using strawpolls to vote on motions, and it becomes quite tedious and difficult to navigate back and forth.
### Context
![image](https://user-images.githubusercontent.com/64384088/97302716-d02be800-182f-11eb-9c34-d4f1eebfff78.png)
![image](https://user-images.githubusercontent.com/64384088/97302834-f487c480-182f-11eb-95b5-a25e3da721fb.png)

We love MunCoordinated because it's so easy to use and super simple in it's UI! I've tried fiddling around with the code myself but I'm not familiar with some of the integrations.

**Comment by MaxwellBo** [comment]
Hi Sharan! This seems like a reasonable feature request! I'm thinking three little clickable buttons on each of the motions that delegates can vote on. 

I'm currently pretty bogged down in work and life admin at the moment, so the earliest this could probably be done is in 3 weeks time. Hopefully ready for your next session 😁

**Comment by SharanVaidy** [comment]
> Hi Sharan! This seems like a reasonable feature request! I'm thinking three little clickable buttons on each of the motions that delegates can vote on.
> 
> I'm currently pretty bogged down in work and life admin at the moment, so the earliest this could probably be done is in 3 weeks time. Hopefully ready for your next session 😁

That's totally fine! Thank you and good luck!

**Comment by MaxwellBo** [comment]
@SharanVaidy I lied! It's pretty much done!

![image](https://user-images.githubusercontent.com/5368490/97421287-70812a00-1960-11eb-81c7-11d4842015b6.png)


https://deploy-preview-122--muncoordinated.netlify.app/committees/kmm-nzo-zewf/motions

^ Mess around with it and tell me if its working the way that you'd expect. Then I'll merge it after a quick review.

**Comment by SharanVaidy** [comment]
Wow! It works great! I am confused by the 1 against and 1 in favour vote already in place? Could you clarify that?

**Comment by MaxwellBo** [comment]
@SharanVaidy Sorry, that was me voting on it from a standard tab and an incognito tab (which clears the local storage ID which would typically prevent me from voting multiple times).

**Comment by SharanVaidy** [comment]
Ah that makes total sense, thank you!

**Comment by SharanVaidy** [comment]
Please let me know when it's up and running, can't wait to have my delegates try this out!

**Comment by MaxwellBo** [comment]
@SharanVaidy Merged!

**Comment by SharanVaidy** [comment]
Awesome thank you!
