### ISSUE TITLE
Add react-helmet titles to all pages

### ISSUE THREAD

**Issue by MaxwellBo** [MaxwellBo/Muncoordinated-2#143]
https://www.npmjs.com/package/react-helmet?fbclid=IwAR1bMp27C-2XM-A-IFT4WRsMzqHdQlPEgt6MDxecrvmZXzhTs4APKb1cf-E

**Comment by AKh-47** [comment]
I Would like to take up this issue. Is there any specific format you want the titles to be in?

**Comment by MaxwellBo** [comment]
@AKh-47 Hey Akhil! Thanks for you offer!

Probably something like

```
Muncoordinated
Onboard - Muncoordinated
Setup - Muncoordinated
Motions - Muncoordinated
<CAUCUS_NAME> - Muncoordinated
<RESOLUTION_NAME> - Muncoordinated
<STRAWPOLL_NAME> - Muncoordinated
Notes - Muncoordinated
Posts - Muncoordinated
Stats - Muncoordinated
Help - Muncoordinated
Settings - Muncoordinated
```

**Comment by AKh-47** [comment]
@MaxwellBo Please help. I cannot run it on my local

`TypeScript error in /home/akhilkala/Desktop/Open Source/Muncoordinated-2/node_modules/jest-diff/build/diffLines.d.ts(8,13):`

What do I do when there is a Type error in node_modules? I would really appreciate the help, I'm new to open source

**Comment by MaxwellBo** [comment]
@AKh-47 I would delete `node_modules` and download everything again.

**Comment by MaxwellBo** [comment]
@AKh-47 what commands are you running to get that error? Also, are you using `yarn` or `npm` (you should use the latest version of `yarn`)?

**Comment by AKh-47** [comment]
@MaxwellBo Ohhh okayy thanks. I was using npm

**Comment by AKh-47** [comment]
Hello, it was a problem with the typescript version.

https://stackoverflow.com/questions/61783437/react-typescript-error-on-build-in-node-modules-jest-diff-build-difflines-d-ts
