### ISSUE TITLE
Shareable link not giving delegates permission to add to speakers list

### ISSUE THREAD

**Issue by amhollandmun** [MaxwellBo/Muncoordinated-2#152]
**Describe the bug**
I created a new committee and shared it with the delegates.  When the delegates try to add themselves to the speakers list the program says that they do not have permission because they are not the owner.  How do I change the settings to allow them to make changes as delegates. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by amhollandmun** [comment]
I am using this version -  (v2.20.12), I am on an iOS, Chrome browser.

**Comment by MaxwellBo** [comment]
Toggle the `Delegates can queue` toggle

![image](https://user-images.githubusercontent.com/5368490/118063119-c472ce00-b3db-11eb-8582-c92689c68026.png)
