### ISSUE TITLE
Can I remove the for, against and neutral feature while choosing speakers to speak in a caucus?

### ISSUE THREAD

**Issue by sumerh12345** [MaxwellBo/Muncoordinated-2#160]
Can yall pls let me know

**Comment by MaxwellBo** [comment]
Nope!

Any reason why? Most people typically just click the `Neutral` button when a speaker position doesn't really matter.

**Comment by sumerh12345** [comment]
Oh okay. The only reason I asked is because the conference I'm moderating has a lot of first-timers, and when I click neutral, delegates often get swayed and speak on the topic with a neutral stance, even after telling them that clicking neutral is just a formality. Nevertheless, thank you for reaching out.

**Comment by MaxwellBo** [comment]
@sumerh12345 Oh that's really interesting! Would never think that would impact how people speak on topics. I'll think about the impact of that in the future if I ever redesign the speaker queue.
