### ISSUE TITLE
Change Format of Committee

### ISSUE THREAD

**Issue by deekshagvpta** [MaxwellBo/Muncoordinated-2#177]
Hey,
I'm using Mun Coordinated but I picked G20 by mistake. I need to change the format to UNSC, but it's not showing me any option to do that. There's no available option to delete a committee either.

**Comment by MaxwellBo** [comment]
Hi @deekshagvpta - I've made a few changes that would alleviate this that I will try and push out soon.

In the meantime I suggest just creating an entirely new committee using the correct template.

**Comment by MaxwellBo** [comment]
Hi @deekshagvpta 

<img width="665" alt="Screen Shot 2022-10-09 at 12 04 55 pm" src="https://user-images.githubusercontent.com/5368490/194732827-0f3aca9e-e9d5-4f5d-b109-c1abe8d7c3c6.png">


Hope this is sufficient
