### ISSUE TITLE
`master` is broken

### ISSUE THREAD

**Issue by MaxwellBo** [MaxwellBo/Muncoordinated-2#178]
The current Cypress tests are [broken](https://dashboard.cypress.io/projects/zxca1q/runs/157/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D&utm_source=github) because of https://github.com/MaxwellBo/Muncoordinated-2/commit/343ca53a1f8d8a1f450e4af00734373064afba4e. In my opinion just adding some extra elements to a page shouldn't break how a dropdown works, but it seems like maybe it's obscured from Cypress somehow:

```
CypressError: Timed out retrying: cy.click() failed because this element:

<input aria-autocomplete="list" autocomplete="off" class="search" tabindex="0" type="text" value="">
is being covered by another element:

<div class="text" role="alert" aria-live="polite" aria-atomic="true">Afghani...</div>
Fix this problem, or use {force: true} to disable error checking.
```

If someone could figure out why they are broken that would be great.

**Comment by shyambh** [comment]
Hi @MaxwellBo , part of my job is writhing and debugging Cypress tests. I would love to help you out with this.

**Comment by MaxwellBo** [comment]
Hi @shyambh! Thanks for taking the time to investigate this!

You're more then welcome to work on this, and it would be a great help! I've been scratching my head trying fix this specific issue.
