### ISSUE TITLE
Move to Vite

### ISSUE THREAD

**Issue by GeordieEK** [MaxwellBo/Muncoordinated-2#195]
**Is your feature request related to a problem? Please describe.**
`create-react-app` is deprecated, `vite` is the way forward

**Comment by MaxwellBo** [comment]
Also we'll need to disable the `CI: false` override when we do this (this is only so the current `create-react-app` warnings don't get coerced to build failing errors)

**Comment by GeordieEK** [comment]
Completed in #204
