### ISSUE TITLE
Allow committees to be deleted

### ISSUE THREAD

**Issue by arielbider** [MaxwellBo/Muncoordinated-2#33]
Hi,
I can't delete a created committee.
Is it even possible to do so?

**Comment by MaxwellBo** [comment]
Hi @arielbider 

It isn't at the moment. Is there any reason you'd like to delete it? Just to clear it from the list that you see at https://muncoordinated.io/committees ?

**Comment by arielbider** [comment]
Hi,

I used the Muncoordinated for a simulation. I have multiple committees with the same name, but with different topics because I could not change the topic or the committee name.
As I don't need the record of these simulations, I would like to delete them.

What else can I do, so I won't see these committees under my account, or to change the names and the topics?

**Comment by MaxwellBo** [comment]
Hi @arielbider, I'll allow you to edit the names and topics ASAP. Should be ready within the hour.

**Comment by MaxwellBo** [comment]
Okay, so you should be able to change the names and topics. Allowing committees to be deleted is a bigger task, but hopefully that's a decent stop-gap.

**Comment by MaxwellBo** [comment]
You'll also need to refresh the app a couple of times to pull the new version.

**Comment by arielbider** [comment]
**Wow**, works very well. I don't think there's a need in deleting a committee in such case.

Thank you so much!

**Comment by MaxwellBo** [comment]
No problem, anytime

**Comment by MaxwellBo** [comment]
Committees are still unable to be deleted - there should be some sort of GitHub-esque "This cannot be reversed. Type the name of the committee to confirm this deletion" with a button somewhere on the settings screen.

**Comment by arielbider** [comment]
> Committees are still unable to be deleted - there should be some sort of GitHub-esque "This cannot be reversed. Type the name of the committee to confirm this deletion" with a button somewhere on the settings screen.

Sounds great!
What about exporting the data before deleting? to excel maybe

**Comment by tanmay2004** [comment]
My issue is because of a similar reason to what @arielbider has talked about here. I was also experimenting with the website and trying to understand how things work. I feel many people interacting with the website for the first time would have to experiment to understand how it works. 

@MaxwellBo, could we perhaps add a "Reset" button? The button could reset all the stats as well as the created Caucuses and Resolutions. Only the setup with the participating countries would remain once Reset is pressed. How does that sound? Also, the button can be added to the settings tab and only be visible to the owner. Thanks.

**Comment by MaxwellBo** [comment]
Hi @tanmay2004!

While not quite committee resetting, the code for committee deletion has been added and is currently in review: https://github.com/MaxwellBo/Muncoordinated-2/pull/157

We're aiming for completion by next Friday.

Sorry for long on this feature, all the current contributors to Muncoordinated have been trying to squeeze in time around work.

**Comment by tanmay2004** [comment]
Okay thanks!
