### ISSUE TITLE
Present & Voting

### ISSUE THREAD

**Issue by arielbider** [MaxwellBo/Muncoordinated-2#34]
Hi,

Since all delegates who are voting are also present, is it possible to do that when I press on voting on the Admin page, it will mark present automatically?

Thanks.

**Comment by MaxwellBo** [comment]
This one will have to be a wontfix. It's quite possible for someone to have marked themselves as present and voting, leave the room, and then come back again - we want to preserve the flag that they were voting. So the idea of being "voting" without being present is very much something that exists, and I don't want to indicate to the user that it isn't.

Secondly, it'd vastly overcomplicate the handling for those two checkboxes.

**Comment by MaxwellBo** [comment]
Oh yeah - for a very long time I didn't realise "voting" meant "being forced to vote for or against", rather than "being able to vote".
