### ISSUE TITLE
Is there any way that the shareable link can keep delegates from editing committee details?

### ISSUE THREAD

**Issue by TheRoman1** [MaxwellBo/Muncoordinated-2#42]
I just started using MUNcoordinated and I really want to use it for the conference that my school is hosting. I think that the idea of delegates being able to add amendments and add themselves to a speaker's list is cool. However, when I try to use the link, the other person is able to change all details of the committee. Is there any way that the shareable link can keep delegates from editing committee details?

**Comment by MaxwellBo** [comment]
Hi @TheRoman1, did you figure out what you needed?

**Comment by TheRoman1** [comment]
I did. Thank you very much

**Comment by TheRoman1** [comment]
I did. Thank you very much
