### ISSUE TITLE
Deleting a Caucus/Resolution

### ISSUE THREAD

**Issue by eos1dx** [MaxwellBo/Muncoordinated-2#50]
Hi! I'm chairing Singapore MUN and I wish to delete resolutions/caucuses as I want to keep the interface clean. 

Is there a way to delete the reso/caucus? Thanks!

**Comment by MaxwellBo** [comment]
Hi @eos1dx! You can't delete resolutions, but you can Close caucuses by clicking the dropdown next to the caucus name, and selecting the "Closed" option. It shouldn't appear in any of the dropdowns

**Comment by eos1dx** [comment]
Can the 'closed' feature also apply to resolutions please. I have accidentally created one and I don't want delegates to see an empty box on the dropdown menu

**Comment by MaxwellBo** [comment]
There should be some way to delete resolutions. I previously had a delete button for resolutions but got rid of it because:

1) It was ugly
2) People were deleting the resolution instead of marking it failed.
