### ISSUE TITLE
Voting results do not tally 

### ISSUE THREAD

**Issue by eos1dx** [MaxwellBo/Muncoordinated-2#51]
Number under 'abstentions' and 'no' is wrong. 
Should be '0' but is '1'.
<img width="783" alt="Screenshot 2019-06-09 at 7 06 41 PM" src="https://user-images.githubusercontent.com/51526953/59158270-1ae97a80-8aea-11e9-8dca-9e56879fab15.png">

**Comment by MaxwellBo** [comment]
Hmmmmm 🤔 that definitely looks like a bug.

**Comment by MaxwellBo** [comment]
@eos1dx That's been fixed now. Refresh the page to download the update.

**Comment by eos1dx** [comment]
Thank you so much! My conference is tomorrow and this software will really help me:)
