### ISSUE TITLE
Voting rules

### ISSUE THREAD

**Issue by eos1dx** [MaxwellBo/Muncoordinated-2#52]
In Singapore (unsure about other MUN circuits), voting rules are such that abstentions do not negate the 2/3s majority. 

Hence, if there are 10 delegates in the council. 7 abstain, and 2 vote in favour and one vote against, the substantive vote should still pass. 

However, currently muncoordinated includes the 7 abstentions in calculating the 2/3s majority. Hence, instead of the results being 2/3=the vote passes, the software thinks it's 2/10 which causes the vote to fail. 

It would be good if there is an option for abstentions to **not** factor into the pass/fail of the vote, as we do it in Singapore. 

Thank you so so much!

**Comment by MaxwellBo** [comment]
I might be able to get this in tomorrow morning (hopefully before you have to vote on any resolutions).

**Comment by MaxwellBo** [comment]
@eos1dx Yo, so this might be a little tricky to implement. Muncoordinated currently has no concept of "end voting", so it checks whether a vote has succeeded or votes by seeing whether the number of votes has or hasn't cleared a certain threshold. In this situation, _there is no such threshold_. The threshold keeps changing every vote that gets cast. It might mean that you get a "PASSED" and the next vote you cast you get a "FAILED".

**Comment by MaxwellBo** [comment]
@eos1dx I've pushed a patch, let me know what you think of it.

**Comment by eos1dx** [comment]
Yes thank you so much for creating a whole separate section for this!
