### ISSUE TITLE
Motion to move to Direct Voting Procedures

### ISSUE THREAD

**Issue by eos1dx** [MaxwellBo/Muncoordinated-2#53]
Some ROPs use the term 'motion to move into direct voting procedures' to end debate on a resolution and vote on it. This is different from the 'motion to close debate' which is to table the topic as a whole. 

I was wondering if it was possible to insert that motion into the motion dropdown list. Preferably, this would also mentions which resolution is being voted upon and allow, if passed, the chair to press a button to directly go to the voting page on the specific resolution (but that is secondary). 

Thank you so so much for being so active in the development and support of this software!!

**Comment by MaxwellBo** [comment]
Can do, I'll add this now, maybe in the next few hours or so

**Comment by MaxwellBo** [comment]
@eos1dx That's been added, let me know what you think

**Comment by eos1dx** [comment]
Thank you so much for the changes! It works perfectly!
