### ISSUE TITLE
Approve and Delete button for some, but not all motions

### ISSUE THREAD

**Issue by MPham95** [MaxwellBo/Muncoordinated-2#7]
As a Director, I can only "approve and delete" "open moderated caucus" and only "delete" "open unmoderated caucus"

**Comment by MaxwellBo** [comment]
Add support for draft resolution motioning in d76841075c1614b2a433f1b4ef4b508c51fa5746

**Comment by MaxwellBo** [comment]
Add support for unmod motioning in 596ed0421620b4be2351a2cde1fa217d70c01758

**Comment by MaxwellBo** [comment]
Add support for caucus closing motioning 484bad0a259f310b9b715464760f4e3221c56371
Add support for unmod extending motioning f1fc93b76c765cf3288b99fbdeecbd9847e8576f
Add support for introducing amendment motioning 13d84960a46bc34fd9c97d7873ac88b61e6251c5

Closed by 13d84960a46bc34fd9c97d7873ac88b61e6251c5
