### ISSUE TITLE
Could we add more states to the Setup list?

### ISSUE THREAD

**Issue by president-zelmun2020** [MaxwellBo/Muncoordinated-2#71]
We are hosting a historical committee where we will have states like USSR, East and West Germany, and Czechoslovakia. I was hoping that these and more historical states could be added to the Setup list with the correct flags.

**Comment by MaxwellBo** [comment]
Hi @president-zelmun2020! I'm a bit antsy about adding historical states, mainly because I want the preset list as a current reflection of the GA. I'll be looking at adding custom flags later on so you won't need presets. (#46).
