### ISSUE TITLE
Committee Types

### ISSUE THREAD

**Issue by MaxwellBo** [MaxwellBo/Muncoordinated-2#81]
When creating a committee, along with selecting the Name, Topic, Chairpeople, and Conference, a Committee Type:

- ECOSOC
- UN General Assembly
- UNHCR
- UNHRC
- UNICEF
- UN Security Council
- WHO Executive Board

etc.

By selecting this, with the exception of the General Assembly, the committee members will be prepopulated in the Setup screen and the appropriate Majority rules will be set for the resolution (if #82) is implemented.

Example from https://session.muncommand.com/setup

![image](https://user-images.githubusercontent.com/5368490/94354976-60f19580-00c3-11eb-8ea6-8daeb319027f.png)
![image](https://user-images.githubusercontent.com/5368490/94355049-f8ef7f00-00c3-11eb-9251-994b7b17f7f4.png)

**Comment by kumar-ish** [comment]
Should the countries be pre-filled and the conference director/user allowed to change what the countries are afterwards without restrictions/reference to what the initial template selection was?

**Comment by MaxwellBo** [comment]
@kumar-ish I'd imagine that's probably what directors would like
